version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: estimate_db
    environment:
      POSTGRES_USER: estimate
      POSTGRES_PASSWORD: estimate
      POSTGRES_DB: estimate
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: estimate_backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app

volumes:
  db_data:

